'use client';

import { KeyRound, Lock, ShieldCheck } from 'lucide-react';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { Suspense, useEffect, useState } from 'react';
import {
  AuthButton,
  AuthInput,
  AuthNotice,
  AuthPanelHeader,
  AuthShell,
  AuthTabs,
} from '@/components/auth/auth-ui';
import { ApiError, apiFetch } from '@/lib/api/client';

function ResetPasswordForm() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [token, setToken] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [notice, setNotice] = useState<string | null>(null);
  const [noticeTone, setNoticeTone] = useState<'warning' | 'success' | 'error'>('warning');
  const [isSubmitting, setIsSubmitting] = useState(false);

  useEffect(() => {
    const t = searchParams.get('token');
    if (t) {
      setToken(t);
    }
  }, [searchParams]);

  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setNotice(null);

    if (!token.trim()) {
      setNoticeTone('error');
      setNotice('Reset token is required.');
      return;
    }

    if (password.length < 8) {
      setNoticeTone('error');
      setNotice('Password must be at least 8 characters long.');
      return;
    }

    if (password !== confirmPassword) {
      setNoticeTone('error');
      setNotice('Passwords do not match.');
      return;
    }

    try {
      setIsSubmitting(true);
      await apiFetch(
        '/auth/reset-password',
        {
          method: 'POST',
          body: JSON.stringify({
            token: token.trim(),
            password,
          }),
        },
        { auth: false },
      );

      setNoticeTone('success');
      setNotice('Password updated successfully! Redirecting to login...');
      setToken('');
      setPassword('');
      setConfirmPassword('');

      setTimeout(() => {
        router.replace('/login');
      }, 1500);
    } catch (requestError: unknown) {
      if (requestError instanceof ApiError) {
        setNoticeTone('error');
        if (requestError.status === 400) {
          setNotice(requestError.message || 'Reset token is invalid or has expired. Please request a new one.');
        } else if (requestError.status === 429) {
          setNotice('Too many attempts. Please wait a minute and try again.');
        } else if (requestError.status >= 500) {
          setNotice('Server error. Please try again later or contact support.');
        } else {
          setNotice(requestError.message || 'Unable to reset password right now.');
        }
      } else {
        setNoticeTone('error');
        setNotice('Network error. Please check your connection and try again.');
      }
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <form className="mt-6 space-y-4" onSubmit={handleSubmit}>
      <AuthInput
        label="Reset token"
        placeholder="Enter 6-digit code"
        value={token}
        onChange={(event) => setToken(event.target.value)}
        icon={<KeyRound size={16} />}
        helper="The alphanumeric recovery token generated by your request."
      />
      <AuthInput
        label="New password"
        placeholder="Enter new password"
        type="password"
        value={password}
        onChange={(event) => setPassword(event.target.value)}
        icon={<Lock size={16} />}
      />
      <AuthInput
        label="Confirm new password"
        placeholder="Confirm new password"
        type="password"
        value={confirmPassword}
        onChange={(event) => setConfirmPassword(event.target.value)}
        icon={<Lock size={16} />}
      />
      {notice ? <AuthNotice message={notice} tone={noticeTone} /> : null}
      <AuthButton
        type="submit"
        label={isSubmitting ? 'Resetting password...' : 'Reset Password'}
        isLoading={isSubmitting}
        disabled={isSubmitting || !token || !password || !confirmPassword}
      />
      <p className="text-center text-xs text-ink-muted">
        Remembered your password?{' '}
        <Link href="/login" className="font-semibold text-ink">
          Return to login
        </Link>
      </p>
    </form>
  );
}

export default function ResetPasswordPage() {
  return (
    <AuthShell
      eyebrow="Account recovery"
      title="Complete your password reset securely."
      subtitle="Input your 6-digit recovery token along with your new password to restore access to your Fleet OS account."
      securityHint="Your connection is fully secure"
      features={[
        {
          icon: <Lock size={16} />,
          title: 'Secure password standards',
          description: 'Passwords must be at least 8 characters with a mix of numbers/letters.',
        },
        {
          icon: <KeyRound size={16} />,
          title: 'One-time tokens',
          description: 'Recovery tokens expire after 1 hour and are invalidated immediately on use.',
        },
        {
          icon: <ShieldCheck size={16} />,
          title: 'Identity protection',
          description: 'All identity actions are audited and logged in the Fleet OS command center.',
        },
      ]}
    >
      <AuthPanelHeader
        eyebrow="Reset password"
        title="Choose a new password"
        description="Provide the code sent to your email or phone, then choose a strong, secure new password."
      />
      <AuthTabs active="login" />
      <Suspense fallback={<p className="text-sm text-ink-muted">Loading reset form...</p>}>
        <ResetPasswordForm />
      </Suspense>
    </AuthShell>
  );
}
