import { PrismaClient, EventType } from '@prisma/client';
import { randomUUID } from 'crypto';
import mqtt from 'mqtt';
import { computePayloadSignature } from '../src/mqtt/mqtt-validation.util';
import { decryptDeviceSecret } from '../src/crypto/device-secret.crypto';
import * as dotenv from 'dotenv';

dotenv.config();

const prisma = new PrismaClient();

interface SimState {
  deviceUid: string;
  secret: string;
  lat: number;
  lng: number;
  speedKph: number;
  heading: number;
  batteryV: number;
  ignition: boolean;
}

// Starting point around Kigali
const START_LAT = -1.944;
const START_LNG = 30.061;

function randomInRange(min: number, max: number): number {
  return Math.random() * (max - min) + min;
}

// Masks device identifiers before logging command output.
function truncateDeviceUid(deviceUid: string): string {
  if (deviceUid.length <= 8) {
    return `${deviceUid.slice(0, 2)}***${deviceUid.slice(-2)}`;
  }
  return `${deviceUid.slice(0, 4)}...${deviceUid.slice(-4)}`;
}

async function main() {
  const masterKey = process.env.DEVICE_SECRET_MASTER_KEY;
  if (!masterKey) {
    throw new Error('DEVICE_SECRET_MASTER_KEY is missing from environment.');
  }

  const mqttUrl = process.env.MQTT_URL ?? 'mqtt://localhost:1883';
  console.log(`Connecting to MQTT broker at ${mqttUrl}...`);
  const client = mqtt.connect(mqttUrl);

  await new Promise<void>((resolve, reject) => {
    client.once('connect', () => resolve());
    client.once('error', (err) => reject(err));
  });
  console.log('Connected to MQTT broker.');

  console.log('Fetching active devices assigned to bikes...');
  const devices = await prisma.device.findMany({
    where: {
      status: 'ACTIVE',
      bikeId: { not: null },
      secretEncrypted: { not: null },
    },
  });

  if (devices.length === 0) {
    console.log('No active devices found. Run the seed script first.');
    process.exit(0);
  }

  console.log(`Found ${devices.length} active devices. Initializing simulation state...`);

  const simStates: SimState[] = devices.map((d) => {
    const secret = decryptDeviceSecret(d.secretEncrypted!, masterKey);
    return {
      deviceUid: d.deviceUid,
      secret,
      lat: START_LAT + randomInRange(-0.05, 0.05),
      lng: START_LNG + randomInRange(-0.05, 0.05),
      speedKph: randomInRange(10, 60),
      heading: randomInRange(0, 360),
      batteryV: randomInRange(40, 54.6), // 48V battery system bounds
      ignition: true,
    };
  });

  console.log('Simulation started. Press Ctrl+C to stop.');

  // Interval for Telemetry: every 3 seconds
  setInterval(() => {
    for (const state of simStates) {
      // Move bike slightly
      const dist = (state.speedKph / 3600) * 3; // km traveled in 3 sec
      const degDist = dist / 111; // rough conversion to degrees

      // Move along heading
      state.lat += degDist * Math.cos(state.heading * (Math.PI / 180));
      state.lng += degDist * Math.sin(state.heading * (Math.PI / 180));

      // Randomly change heading and speed slightly
      state.heading = (state.heading + randomInRange(-10, 10)) % 360;
      state.speedKph = Math.max(0, Math.min(80, state.speedKph + randomInRange(-5, 5)));
      
      // Slowly drain battery
      state.batteryV = Math.max(40, state.batteryV - 0.005);

      const unsignedPayload = {
        ts: new Date().toISOString(),
        lat: state.lat,
        lng: state.lng,
        speedKph: state.speedKph,
        heading: state.heading,
        batteryV: state.batteryV,
        ignition: state.ignition,
        nonce: randomUUID(),
      };

      const sig = computePayloadSignature(state.secret, unsignedPayload);
      const payload = { ...unsignedPayload, sig };
      const topic = `v1/devices/${state.deviceUid}/telemetry`;

      client.publish(topic, JSON.stringify(payload), { qos: 1 }, (err) => {
        if (err) console.error(`Error publishing telemetry for ${state.deviceUid}`, err);
      });
    }
  }, 3000);

  // Interval for Events: every 10 seconds, pick a random bike to have an incident
  setInterval(() => {
    if (Math.random() > 0.5) { // 50% chance every 10s
      const randomState = simStates[Math.floor(Math.random() * simStates.length)];
      const eventTypes = [
        { type: EventType.CRASH, severity: 'CRITICAL' },
        { type: EventType.SOS, severity: 'CRITICAL' },
        { type: EventType.OVERSPEED, severity: 'HIGH' },
        { type: EventType.HARSH_BRAKE, severity: 'MEDIUM' },
        { type: EventType.THEFT_SUSPECTED, severity: 'HIGH' },
      ];
      const randomEvent = eventTypes[Math.floor(Math.random() * eventTypes.length)];

      const unsignedEvent = {
        ts: new Date().toISOString(),
        type: randomEvent.type,
        severity: randomEvent.severity,
        meta: { simulated: true, note: 'Generated by fleet simulator' },
        nonce: randomUUID(),
      };

      const sig = computePayloadSignature(randomState.secret, unsignedEvent);
      const payload = { ...unsignedEvent, sig };
      const topic = `v1/devices/${randomState.deviceUid}/event`;

      client.publish(topic, JSON.stringify(payload), { qos: 1 }, (err) => {
        if (err) {
          console.error(`Error publishing event for ${randomState.deviceUid}`, err);
        } else {
          console.log(`⚠️ Published ${randomEvent.type} event for ${truncateDeviceUid(randomState.deviceUid)}`);
        }
      });
    }
  }, 10000);
}

main().catch((err) => {
  console.error('Simulation failed:', err);
  process.exit(1);
});
