-- AlterTable
ALTER TABLE "RegistrationInvite" ADD COLUMN IF NOT EXISTS "maxUses" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "RegistrationInvite" ADD COLUMN IF NOT EXISTS "usedCount" INTEGER NOT NULL DEFAULT 0;
